version: '3'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    
  ec-api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    volumes:
      - .:/ec_api
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - pg
    tty: true
volumes:
  bundle:
  postgres_volume: