version: '3'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
			TZ: Asia/Tokyo
    expose:
      - 5432  
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
	  image: redis
    environment:
		  TZ: Asia/Tokyo
		expose:
		  - 6379
    volumes:
      - redis_volume:/data
      
  ec-api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    volumes:
      - .:/ec_api
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - pg
    tty: true
    
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq -C conifg/sidekiq.yml
    depends_on:
      - ec-api
      - pg
      - redis
    environment:
      TZ: Asia/Tokyo
    volumes:
      - sidekiq_bundle:/usr/local/bundle
      
volumes:
  bundle:
  postgres_volume:
  redis_volume:
  sidekiq_bundle